[package]
name = "hot_patatoe_srv"
version = "0.1.0"
authors = [
            "Paul Barrié <paul.barrie.calmels@gmail.com>",
            "Paolo Manoas<>",
            "Adem Mrizak <>"
        ]

edition = "2021"

[dependencies]
tokio = { version = "0.2", features = ["full"] }
warp = "0.2"
