[package]
name = "shared"
version = "0.1.0"
authors = [
    "Paul Barrié <paul.barrie.calmels@gmail.com>",
    "Paolo Manaois<>",
    "Adem Mrizak <>"
]

edition = "2021"

[dependencies]
serde = { version = "1.0.1", features = ["derive"] }
